services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: problem-piper
          property: connectionString

databases:
  - name: problem-piper
    databaseName: problem-piper
    user: sahil
